#!/bin/bash

 ######   #######  ##    ## ######## ####  ######   
##    ## ##     ## ###   ## ##        ##  ##    ##  
##       ##     ## ####  ## ##        ##  ##        
##       ##     ## ## ## ## ######    ##  ##   #### 
##       ##     ## ##  #### ##        ##  ##    ##  
##    ## ##     ## ##   ### ##        ##  ##    ##  
 ######   #######  ##    ## ##       ####  ######   

user_name=frosty

dwm=false
slim=true
subtle=false
syslinux=true
utils=true
virtualize=true
xfce=true
xorg=true

frostyrepo=false


##     ## ######## ##       ########  ######## ########   ######  
##     ## ##       ##       ##     ## ##       ##     ## ##    ## 
##     ## ##       ##       ##     ## ##       ##     ## ##       
######### ######   ##       ########  ######   ########   ######  
##     ## ##       ##       ##        ##       ##   ##         ## 
##     ## ##       ##       ##        ##       ##    ##  ##    ## 
##     ## ######## ######## ##        ######## ##     ##  ######  

function istrue() {
	[ "$1" = true ]
	return $?
}


#### ##    ##  ######  ########    ###    ##       ##       
 ##  ###   ## ##    ##    ##      ## ##   ##       ##       
 ##  ####  ## ##          ##     ##   ##  ##       ##       
 ##  ## ## ##  ######     ##    ##     ## ##       ##       
 ##  ##  ####       ##    ##    ######### ##       ##       
 ##  ##   ### ##    ##    ##    ##     ## ##       ##       
#### ##    ##  ######     ##    ##     ## ######## ######## 

pacstrap /mnt base || exit 1
packages=()
	#packages+=('')

if istrue $dwm; then
	packages+=('dwm')
	packages+=('xautolock')
	packages+=('slock')
fi
if istrue $slim; then
	packages+=('slim')
fi
if istrue $subtle; then
	packages+=('subtle')
fi
if istrue $syslinux; then
	packages+=('syslinux')
fi
if istrue $utils; then
	packages+=('vim')
	packages+=('git')
	packages+=('zsh')
	packages+=('tmux')
	packages+=('screen')
	packages+=('openssh')
	packages+=('htop')
	packages+=('lsof')
	packages+=('samba')
	packages+=('ncdu')
	packages+=('tree')
	packages+=('nfs-utils')
	packages+=('sudo')
	packages+=('python')
	packages+=('abs')
	packages+=('base-devel')
	packages+=('mpd')
	packages+=('ncmpcpp')
	packages+=('sshfs')
	packages+=('bridge-utils')
	packages+=('openbsd-netcat')
	packages+=('rxvt-unicode')
	packages+=('syslog-ng')
	packages+=('logrotate')
fi
if istrue $virtualize; then
	packages+=('libvirt')
	packages+=('virtualbox')
	packages+=('virt-manager')
	packages+=('virt-viewer')
	packages+=('qemu')
fi
if istrue $xfce; then
	packages+=('xfce4')
fi
if istrue $xorg; then
	packages+=(xorg-server{,-utils})
	packages+=(xf86-video-{intel,nouveau})
	packages+=('xscreensaver')
	packages+=('chromium')
	packages+=('firefox-developer')
fi

if istrue $frostyrepo && (grep -v frostyfrog /etc/pacman.conf); then
	sed "/\[core/i [frostyrepo]\nServer = http://repo.frostyfrog.net/\n\n" /etc/pacman.conf
fi

pacman -Syy ${packages[*]}

 ######  ######## ######## ##     ## ########  
##    ## ##          ##    ##     ## ##     ## 
##       ##          ##    ##     ## ##     ## 
 ######  ######      ##    ##     ## ########  
      ## ##          ##    ##     ## ##        
##    ## ##          ##    ##     ## ##        
 ######  ########    ##     #######  ##        

echo -e 'LANG="en_US.UTF-8"\nLC_COLLATE="C"'>> /mnt/etc/locale.conf
sed -i 's/^#\(en_US\|ja_JP\)/\1/' /mnt/etc/locale.gen
cat <<EOCHROOT | arch-chroot /mnt

function istrue() {
	[ "\$1" = true ]
	return \$?
}

pacman-key init
pacman-key --populate archlinux
pacman-key -r 0x362db4a50060df7b

if istrue $frostyrepo; then
	sed "/\\[core/i [frostyrepo]\\nSigLevel = Required\\nServer = http://repo.frostyfrog.net/\\n\\n" -i /etc/pacman.conf
fi

mkinitcpio -p linux
locale-gen
ln -s /usr/share/zoneinfo/America/Denver /etc/localtime

if istrue $virtualize; then
	groupadd libvirt
fi

cat <<EOF > /etc/polkit-1/rules.d/50-org.libvirt.unix.manage.rules
polkit.addRule(function(action, subject) {
	if (action.id == "org.libvirt.unix.manage" &&
	    subject.isInGroup("libvirt")) {
		return polkit.Result.Yes;
	}
});
EOF

useradd -m -G wheel,users,systemd-journal -s /bin/zsh frosty

if istrue $utils; then
	gpasswd -a $user_name mpd
fi
if istrue $virtualize; then
	gpasswd -a $user_name vboxusers
	gpasswd -a $user_name libvirt
fi

cat <<EOSU | su - $user_name
	git clone https://github.com/frostyfrog/dotfiles.git .files
	cd .files
	git submodule update --init --recursive
	./autocopy
EOSU

mkdir -p /var/lib/mpd/music/music
ln -s /var/lib/mpd/music/music /home/$user_name/music
chown $user_name:users /home/$user_name/music
chown $user_name:users /var/lib/mpd/music/music

if istrue $utils; then
	systemctl enable sshd mpd
fi
if istrue $slim; then
	systemctl enable slim
fi
if istrue $virtualize; then
	systemctl enable libvirtd
fi

if istrue $syslinux; then
	syslinux-install_update -i -a -m
fi

EOCHROOT

genfstab -p /mnt >> /mnt/etc/fstab

echo <<EOF
Please change the password of "$user_name"
Please correct the config in /boot/syslinux/syslinux.conf
EOF

# vim: set ai ft=sh syntax=sh :
