echo -e "\e[31mHello World\e[0m"
echo -e "\033[31mHello\e[0m World"
echo -e "Normal \e[1mBold"
echo -e "Normal \e[2mDim"
echo -e "Normal \e[4mUnderlined"
echo -e "Normal \e[5mBlink"
echo -e "Normal \e[7minverted"
echo -e "Normal \e[8mHidden"
echo -e "\e[0mNormal Text"
echo -e "Normal \e[1mBold \e[21mNormal"
echo -e "Normal \e[2mDim \e[22mNormal"
echo -e "Normal \e[4mUnderlined \e[24mNormal"
echo -e "Normal \e[5mBlink \e[25mNormal"
echo -e "Normal \e[7minverted \e[27mNormal"
echo -e "Normal \e[8mHidden \e[28mNormal"
echo "Source: http://misc.flogisoft.com/bash/tip_colors_and_formatting"
