#!/bin/bash

if [ -n "${DISPLAY+x}" ]; then
	echo 'Display set :D'
else
	export DISPLAY=:0
fi

laptopScreen=LVDS2
externalScreen=VGA-1-0
screenRes=1600x900

screenResPos=${screenRes%x*}x0

function projector() {
	xrandr --output $laptopScreen --off --output $externalScreen --auto
	synergyf
}
function smallProjector() {
	xrandr --output $externalScreen --mode $screenRes --output $laptopScreen --off
	synergyf
}
function netbook() {
	xrandr --output $externalScreen --off --output $laptopScreen --auto
	synergyf
}
function both() {
        xrandr --output $externalScreen --auto --pos $screenResPos
	xrandr --output $laptopScreen --auto
        synergyf
}

function bothr() {
	xrandr --output $laptopScreen --auto --pos 1280x0
	xrandr --output $externalScreen --auto
	synergyf
}

function  synergyf() {
	PID=`pidof -o %PPID synergyc`
	[ ! -z "$PID" ] && kill $PID &> /dev/null
	if [ $? -gt 0 ] && [ ! -z "$PID" ]; then
		echo "Failed to stop Synergy"
	else
		sleep 1
		#synergyc 192.168.0.140
		#synergyc --crypto-mode cfb --crypto-pass SoRaNoWoTo 10.10.9.88
		#synergyc 10.10.9.88
	fi
}
case $@ in
	n2p)
		projector;;
	n2sp)
		smallProjector;;
	p2n)
		netbook;;
	both)
		both;;
	bothr)
		bothr;;
	*);;
esac
