#!/bin/bash
sudo pkill wpa_supplicant
sleep 1
sudo pkill dhcpcd
#sudo ifconfig wlan0 down
sudo ip addr flush dev eth0
sudo ip addr flush dev wlan0
sudo ip link set dev eth0 down
sudo ip link set dev wlan0 down
