#!/bin/bash
#for file in ./*.mp4
#do
#	cp "${file}" /usb/chinese
#done
colors=(
"\e[0;30m"
"\e[0;31m"
"\e[0;32m"
"\e[0;33m"
"\e[0;34m"
"\e[0;35m"
"\e[0;36m"
"\e[0;37m"
"\e[1;30m"
"\e[1;31m"
"\e[1;32m"
"\e[1;33m"
"\e[1;34m"
"\e[1;35m"
"\e[1;36m"
"\e[1;37m"
)

let R=$RANDOM%16+0;color=${colors[$R]};
echo -ne "${color}YAY!\e[0m "
